name: 🚀 Deploy NestJS Blog Backend API to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: J1726391673
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "/home/J1726391673/posts_api"

      - name: Run deploy commands on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: J1726391673
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e
            cd /home/J1726391673/posts_api
            
            # Detener proceso previo si existe
            sudo lsof -t -i:3000 | xargs -r sudo kill -9 || true
            
            # Crear archivo de variables de entorno
            printf "%s" "${{ secrets.ENV_FILE }}" > .env
            
            # Instalar dependencias y construir
            npm install
            npm run build
            
            # Gestionar proceso con PM2
            pm2 stop nestjs-posts-api || true
            pm2 delete nestjs-posts-api || true
            pm2 start dist/main.js --name nestjs-posts-api
            pm2 save